### ISSUE TITLE
KMYF-Montgomery Field Airport-CALIFORNIA-USA

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Airports#510]
So-Cali, Redo may be needed. Misalingment not uniform.

**Comment by Adam167** [comment]
I'll do this

**Comment by kilt46** [comment]
![image](https://cloud.githubusercontent.com/assets/14023167/19614456/ff6f4516-97ba-11e6-8344-5f222db515b5.png)

**Comment by RyanEpps** [comment]
Airport needs reworked up to new standards and additional spawns.

**Comment by jakey200** [comment]
I will redo this.
🙃

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/83357883-e2633200-a334-11ea-8c01-cb9b0f8ba0d6.png)

**Comment by MajorTomMueller** [comment]
Duplicate spawn names:
https://gist.github.com/carmichaelalonso/652d032d7fe3683cbf8d88365ff5a690

**Comment by jakey200** [comment]
fixed

**Comment by MajorTomMueller** [comment]
still a bunch:
https://gist.github.com/662f30e2ffa2065a932f7a9f103d14c6

**Comment by MajorTomMueller** [comment]
I have done all the airports where you have left only one or two, but this one is still yours

**Comment by MajorTomMueller** [comment]
Has still some in latest error file

**Comment by jakey200** [comment]
I know, I fixed and sent to OR but it has not been added yet.

**Comment by MajorTomMueller** [comment]
Still persistent in error list:
https://gist.github.com/carmichaelalonso/bd54fd4eec434da4905cc6633b9a73a3

**Comment by jakey20** [comment]
Because nobody has gotten to it in OR

**Comment by MajorTomMueller** [comment]
And you know that because...?

**Comment by jakey20** [comment]
Because I'm the one who sent it to OR nearly a month ago and nobody has committed it.

**Comment by MBeringuy** [comment]
Duplicate spawns fixed.

**Comment by kilt46** [comment]
![image](https://user-images.githubusercontent.com/14023167/88736320-40768080-d0fe-11ea-8643-2c68433c03d2.png)
